const dateFormat = {
  dateFormat: "dd MMMM yyyy",
  locale: "es",
};

const reportsData = [
  {
    id: 1,
    name: "Aprobación de gastos de viajes",
    type: "Pago",
    category: "Gastos Corporativos",
    steps: [
      { level: 1, role: "Gerente de Finanzas" },
      { level: 2, role: "Director Financiero" },
    ],
    active: true,
  },
  {
    id: 2,
    name: "Aprobación de compras mayores a $10,000",
    type: "Compra",
    category: "Compras",
    steps: [
      { level: 1, role: "Supervisor de Compras" },
      { level: 2, role: "Gerente General" },
    ],
    active: false,
  },
  {
    id: 3,
    name: "Autorización de presupuesto de marketing",
    type: "Presupuesto",
    category: "Marketing",
    steps: [
      { level: 1, role: "Jefe de Marketing" },
      { level: 2, role: "CFO" },
      { level: 3, role: "CEO" },
    ],
    active: true,
  },
  {
    id: 4,
    name: "Aprobación de contratos legales",
    type: "Contrato",
    category: "Legales",
    steps: [
      { level: 1, role: "Asesor Legal" },
      { level: 2, role: "Director Legal" },
    ],
    active: true,
  },
  {
    id: 5,
    name: "Aprobación de beneficios para empleados",
    type: "Revisión",
    category: "Recursos Humanos",
    steps: [
      { level: 1, role: "Gerente de Recursos Humanos" },
      { level: 2, role: "Director General" },
    ],
    active: true,
  },
  {
    id: 6,
    name: "Autorización de reembolsos",
    type: "Pago",
    category: "Finanzas",
    steps: [
      { level: 1, role: "Contador" },
      { level: 2, role: "Gerente de Finanzas" },
    ],
    active: false,
  },
  {
    id: 7,
    name: "Aprobación de proyectos tecnológicos",
    type: "Proyecto",
    category: "Tecnología",
    steps: [
      { level: 1, role: "Líder Técnico" },
      { level: 2, role: "CTO" },
    ],
    active: true,
  },
  {
    id: 8,
    name: "Autorización para eventos corporativos",
    type: "Presupuesto",
    category: "Eventos",
    steps: [
      { level: 1, role: "Gerente de Marketing" },
      { level: 2, role: "CFO" },
    ],
    active: true,
  },
  {
    id: 9,
    name: "Revisión de acuerdos con proveedores",
    type: "Contrato",
    category: "Compras",
    steps: [
      { level: 1, role: "Supervisor de Compras" },
      { level: 2, role: "Director Financiero" },
    ],
    active: false,
  },
  {
    id: 10,
    name: "Aprobación de desarrollo de nuevos productos",
    type: "Proyecto",
    category: "Innovación",
    steps: [
      { level: 1, role: "Gerente de Innovación" },
      { level: 2, role: "Director General" },
    ],
    active: true,
  },
];

const reports = [
  {
    id: 1,
    fecha: "2024-11-01",
    cliente: "Juan Pérez",
    estado: "Realizado",
    monto: 120.4,
    metodoPago: "Transferencia Bancaria",
    fechaConciliacion: "2024-11-02",
  },
  {
    id: 2,
    fecha: "2024-11-02",
    cliente: "María Gómez",
    estado: "Pendiente",
    monto: 300.45,
    metodoPago: "Tarjeta de Crédito",
    fechaConciliacion: null,
  },
  {
    id: 3,
    fecha: "2024-11-03",
    cliente: "Carlos Díaz",
    estado: "Fallido",
    monto: 450.1,
    metodoPago: "PayPal",
    fechaConciliacion: null,
  },
  {
    id: 4,
    fecha: "2024-11-04",
    cliente: "Lucía Ramírez",
    estado: "Realizado",
    monto: 250.4,
    metodoPago: "Efectivo",
    fechaConciliacion: "2024-11-05",
  },
  {
    id: 5,
    fecha: "2024-11-05",
    cliente: "Roberto López",
    estado: "Pendiente",
    monto: 500.0,
    metodoPago: "Transferencia Bancaria",
    fechaConciliacion: null,
  },
  {
    id: 6,
    fecha: "2024-11-06",
    cliente: "Ana Torres",
    estado: "Realizado",
    monto: 100.3,
    metodoPago: "Tarjeta de Débito",
    fechaConciliacion: "2024-11-07",
  },
  {
    id: 7,
    fecha: "2024-11-07",
    cliente: "Diego Martínez",
    estado: "Fallido",
    monto: 400.0,
    metodoPago: "PayPal",
    fechaConciliacion: null,
  },
  {
    id: 8,
    fecha: "2024-11-08",
    cliente: "Elena Hernández",
    estado: "Realizado",
    monto: 350.1,
    metodoPago: "Transferencia Bancaria",
    fechaConciliacion: "2024-11-09",
  },
  {
    id: 9,
    fecha: "2024-11-09",
    cliente: "José Calderón",
    estado: "Pendiente",
    monto: 150.78,
    metodoPago: "Efectivo",
    fechaConciliacion: null,
  },
  {
    id: 10,
    fecha: "2024-11-10",
    cliente: "Patricia Vega",
    estado: "Fallido",
    monto: 600.14,
    metodoPago: "Tarjeta de Crédito",
    fechaConciliacion: null,
  },
  {
    id: 11,
    fecha: "2024-11-11",
    cliente: "Manuel Ortega",
    estado: "Realizado",
    monto: 200.56,
    metodoPago: "Transferencia Bancaria",
    fechaConciliacion: "2024-11-12",
  },
  {
    id: 12,
    fecha: "2024-11-12",
    cliente: "Gabriela Castro",
    estado: "Pendiente",
    monto: 275.0,
    metodoPago: "PayPal",
    fechaConciliacion: null,
  },
  {
    id: 13,
    fecha: "2024-11-13",
    cliente: "Héctor Morales",
    estado: "Realizado",
    monto: 425.0,
    metodoPago: "Efectivo",
    fechaConciliacion: "2024-11-14",
  },
  {
    id: 14,
    fecha: "2024-11-14",
    cliente: "Natalia Rojas",
    estado: "Fallido",
    monto: 325.23,
    metodoPago: "Tarjeta de Débito",
    fechaConciliacion: null,
  },
  {
    id: 15,
    fecha: "2024-11-15",
    cliente: "Pedro León",
    estado: "Realizado",
    monto: 150.17,
    metodoPago: "Transferencia Bancaria",
    fechaConciliacion: "2024-11-16",
  },
];

const users = [
  {
    id: 1,
    name: "John Doe",
    displayName: "johndoe",
    accountNumber: "1234567890",
    externalId: "ext123",
    status: true,
    statusAll: true,
    nomina: 3500,
  },
  {
    id: 2,
    name: "Jane Smith",
    displayName: "janesmith",
    accountNumber: "2345678901",
    externalId: "ext234",
    status: false,
    statusAll: false,
    nomina: 4200,
  },
  {
    id: 3,
    name: "Carlos García",
    displayName: "carlosg",
    accountNumber: "3456789012",
    externalId: "ext345",
    status: true,
    statusAll: true,
    nomina: 4000,
  },
  {
    id: 4,
    name: "Emily Johnson",
    displayName: "emilyj",
    accountNumber: "4567890123",
    externalId: "ext456",
    status: true,
    statusAll: true,
    nomina: 4700,
  },
  {
    id: 5,
    name: "Michael Brown",
    displayName: "mikeb",
    accountNumber: "5678901234",
    externalId: "ext567",
    status: false,
    statusAll: false,
    nomina: 3000,
  },
  {
    id: 6,
    name: "Laura Wilson",
    displayName: "lauraw",
    accountNumber: "6789012345",
    externalId: "ext678",
    status: true,
    statusAll: true,
    nomina: 3900,
  },
  {
    id: 7,
    name: "Pedro Martínez",
    displayName: "pedrom",
    accountNumber: "7890123456",
    externalId: "ext789",
    status: true,
    statusAll: true,
    nomina: 4500,
  },
  {
    id: 8,
    name: "Sara López",
    displayName: "saral",
    accountNumber: "8901234567",
    externalId: "ext890",
    status: true,
    statusAll: true,
    nomina: 4100,
  },
  {
    id: 9,
    name: "David Miller",
    displayName: "davidm",
    accountNumber: "9012345678",
    externalId: "ext901",
    status: false,
    statusAll: false,
    nomina: 2800,
  },
  {
    id: 10,
    name: "Ana Pérez",
    displayName: "anap",
    accountNumber: "0123456789",
    externalId: "ext012",
    status: true,
    statusAll: true,
    nomina: 3600,
  },
  {
    id: 11,
    name: "Lucas Díaz",
    displayName: "lucasd",
    accountNumber: "1234509876",
    externalId: "ext111",
    status: true,
    statusAll: true,
    nomina: 4700,
  },
  {
    id: 12,
    name: "Sophia Torres",
    displayName: "sophiat",
    accountNumber: "2345609876",
    externalId: "ext222",
    status: false,
    statusAll: false,
    nomina: 3900,
  },
  {
    id: 13,
    name: "Miguel Hernández",
    displayName: "miguelh",
    accountNumber: "3456709876",
    externalId: "ext333",
    status: true,
    statusAll: true,
    nomina: 4300,
  },
  {
    id: 14,
    name: "Clara Navarro",
    displayName: "claran",
    accountNumber: "4567809876",
    externalId: "ext444",
    status: true,
    statusAll: true,
    nomina: 3400,
  },
  {
    id: 15,
    name: "Andrés Gómez",
    displayName: "andresg",
    accountNumber: "5678909876",
    externalId: "ext555",
    status: false,
    statusAll: false,
    nomina: 3200,
  },
  {
    id: 16,
    name: "Marta Rivera",
    displayName: "martar",
    accountNumber: "6789009876",
    externalId: "ext666",
    status: true,
    statusAll: true,
    nomina: 3900,
  },
  {
    id: 17,
    name: "Tomás Álvarez",
    displayName: "tomasa",
    accountNumber: "7890109876",
    externalId: "ext777",
    status: true,
    statusAll: true,
    nomina: 4500,
  },
  {
    id: 18,
    name: "Isabel Romero",
    displayName: "isabelr",
    accountNumber: "8901209876",
    externalId: "ext888",
    status: true,
    statusAll: true,
    nomina: 4100,
  },
  {
    id: 19,
    name: "Kevin Ruiz",
    displayName: "kevinr",
    accountNumber: "9012309876",
    externalId: "ext999",
    status: false,
    statusAll: false,
    nomina: 2900,
  },
  {
    id: 20,
    name: "María Ortiz",
    displayName: "mariao",
    accountNumber: "0123409876",
    externalId: "ext000",
    status: true,
    statusAll: true,
    nomina: 3700,
  },
];

export { dateFormat, reportsData, reports, users };
