import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const satoshi = localFont({ src: './assets/fonts/Satoshi_Complete/Fonts/Satoshi-Variable.ttf' })

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App BDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>{children}</body>
    </html>
  );
}
